version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: docmind-postgres
    restart: always
    environment:
      POSTGRES_USER: docmind
      POSTGRES_PASSWORD: docmind_pass
      POSTGRES_DB: docmind_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: